services:
  - type: web
    name: jdf-fitness-tracker
    env: python
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gthread --workers 1 --threads 2 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
